### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by kriztan** [tengel/wetterbot#1]
Can you write a readme how to install this bot?

**Comment by tengel** [comment]
To run the bot just enter the credentials of an existing jabber 
account in data/config.txt and run src/wetterbot.py.
If you like to try the bot without running it: An instance of the bot 
is running on wetterbot@jabber.ccc.de.

**Comment by kriztan** [comment]
Thank for your help, but I'm always getting the following error:

Traceback (most recent call last):
  File "./wetterbot.py", line 163, in <module>
    wetterbot.run()
  File "./wetterbot.py", line 114, in run
    self.jabclnt.shutdown()
AttributeError: WetterBot instance has no attribute 'jabclnt'

Do you have an idea?

**Comment by tengel** [comment]
Apparently the bot is unable to connect to the xmpp server. There 
should be a message in wetterbot.log.
I fixed a bug which might be responsible for the problem. There is an 
option xmppdebug on config.txt now. If set to True, lot of debug 
information is printed to stderr.

**Comment by kriztan** [comment]
Thanks a  lot, I've got it working!
